version: '3'
services:
  iqfeed:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IQFEED_PRODUCT_ID=$IQFEED_PRODUCT_ID
      - IQFEED_LOGIN=$IQFEED_LOGIN
      - IQFEED_PASSWORD=$IQFEED_PASSWORD
