version: '3'
services:
  iqfeed:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IQFEED_PRODUCT_ID: "CHANGEME"
      IQFEED_LOGIN: "CHANGEME"
      IQFEED_PASSWORD: "CHANGEME"
